<!--XML file using a DTD-->
<!DOCTYPE layout [
<!ELEMENT layout (screen)+ > 
<!ELEMENT screen ((field)+,(table)*,(message)*) >
<!ATTLIST screen
	  name CDATA #REQUIRED 
	  version CDATA #REQUIRED >
<!ELEMENT field EMPTY>
<!ATTLIST field
          name CDATA #REQUIRED 
          x  CDATA #REQUIRED
          y  CDATA #REQUIRED
          length CDATA #REQUIRED
          matchText CDATA #REQUIRED >
<!ELEMENT message EMPTY>
<!ATTLIST message
          name CDATA #REQUIRED 
          msg  CDATA #REQUIRED >        
<!ELEMENT table (col)+ >
<!ATTLIST table
	  name CDATA #REQUIRED
	  numRows CDATA #REQUIRED
	  numColumns CDATA #REQUIRED
	  numPages CDATA #REQUIRED
	  numSections CDATA #REQUIRED
	  startingrowx CDATA #REQUIRED 
      rowsPerRecord CDATA #IMPLIED>
<!ELEMENT col EMPTY>
<!ATTLIST col
          name CDATA #REQUIRED
          x	 CDATA #IMPLIED 
          y  CDATA #REQUIRED
          length CDATA #REQUIRED
          matchText CDATA #REQUIRED
		  rowRecord CDATA #IMPLIED	 >
 ]>        
<layout>
<screen name="FREIGHTBILL" version="2.0.0">
<field name="PRO"               x="1" y="" length="" matchText="Edit1" />
    <field name="CorrectionRequest" x="1" y="" length="" matchText="Edit5" />
    <field name="DISPLAYCLEAR"      x="1" y="" length="" matchText="" />
    <field name="SANDBOX"           x="1" y="" length="" matchText="goober" />
    <field name="WAITPROCLEAR"      x="1" y="" length="" matchText="" />
    <field name="FLEXBOX"           x="1" y="" length="" matchText="VSFlexGrid8L1" />
    <field name="FLEXBOXSUB"        x="1" y="" length="" matchText="VSFlexGrid8Latl1" />
    <field name="TOPLINE"           x="1" y="" length="" matchText="Button33" />
    <field name="DISPLAY"           x="1" y="" length="" matchText="Button57" />
    <field name="WAIT"              x="1" y="" length="" matchText="Edit117" />
    <field name="OREV"              x="1" y="" length="" matchText="Edit105" />
    <field name="CLEAR"             x="1" y="" length="" matchText="Button42" />
    <field name="ALTL"              x="1" y="" length="" matchText="Button50" />
    <field name="BILLAMT"           x="1" y="" length="" matchText="Edit105" />
    <field name="ADDLINE"           x="1" y="" length="" matchText="Button37" />
    <field name="AMT"               x="1" y="" length="" matchText="Edit38" />
    <field name="AUTORATER"         x="1" y="" length="" matchText="Button41" />
    <field name="ACCEPTALL"         x="1" y="" length="" matchText="Button59" />
    <field name="NEWREV"            x="1" y="" length="" matchText="Edit113_DBsays_use_Edit105_not_edit113" />
    <message name="FLEX_VICH" msg="VICH" />
    <message name="FLEX_CORR" msg="CORR" />
    <message name="FLEX_XLGH" msg="XLGH" />
    <message name="FLEX_CLAS" msg="CLAS" />
    <message name="FLEX_TERM" msg="TERM" />
    <message name="FLEX_OREV" msg="OREV" />
    <message name="FLEX_CUBE" msg="CUBE" />
    <message name="FLEX_RMK" msg="RMK" />
    <message name="FLEX_INSP" msg="INSP" />
    <message name="CORRECTION_REQUEST_MSG" msg="AUTO INSPECTION ENTRY" />
    <message name="PROCESSING_OK" msg="PROCESSING OK" />
  </screen>
  <screen name="WINDOWSLOGIN" version="3.0.0">
    <field name="dummy"           x="1" y="" length="" matchText="dummy" />
  </screen>
  <screen name="PRISMLOGIN" version="3.0.0">
    <field name="banner" x="8" y="33" length="15" matchText="FEDERAL EXPRESS" />
    <field name="userId" x="7" y="2" length="7" matchText="USER ID" />
    <field name="password" x="7" y="43" length="" matchText="" />
    <field name="successLoginScreen" x="14" y="15" length="38" matchText="ENTER THE NUMBER OF THE DESIRED SYSTEM" />
    <field name="pricingPrimaryMenuScreen" x="2" y="35" length="9" matchText="P R I S M" />
    <message name="LOGOFF_STRING" msg="LOGOFF" />
    <message name="PRICING_PRIMARY_MENU" msg="1" />
  </screen>
  <screen name="EXPRESSLOGIN" version="3.0.0">
    <field name="banner" x="8" y="33" length="15" matchText="FEDERAL EXPRESS" />
    <field name="userId" x="7" y="2" length="7" matchText="USER ID" />
    <field name="password" x="7" y="43" length="" matchText="" />
    <field name="successLoginScreen" x="14" y="15" length="38" matchText="ENTER THE NUMBER OF THE DESIRED SYSTEM" />
    <field name="ASAPMenuScreen" x="5" y="2" length="38" matchText="ENTER THE NUMBER OF THE DESIRED SYSTEM" />
    <field name="pricingPrimaryMenuScreen" x="2" y="31" length="20" matchText="PRICING PRIMARY MENU" />
    <message name="gotoASAPCommand" msg="ASAP" />    
    <message name="gotoVENDORSCommand" msg="VENDORS" />
    <message name="LOGOFF_STRING" msg="LOGOFF" />
    <message name="PRICING_PRIMARY_MENU" msg="66" />
  </screen>
  <screen name="ABINITIOLOGIN" version="3.0.0">
    <field name="banner" x="8" y="33" length="15" matchText="FEDERAL EXPRESS" />
    <field name="userId" x="7" y="2" length="7" matchText="USER ID" />
    <field name="password" x="7" y="43" length="" matchText="" />
    <field name="successLoginScreen" x="14" y="15" length="38" matchText="ENTER THE NUMBER OF THE DESIRED SYSTEM" />
    <field name="ASAPMenuScreen" x="5" y="2" length="38" matchText="ENTER THE NUMBER OF THE DESIRED SYSTEM" />
    <field name="pricingPrimaryMenuScreen" x="2" y="31" length="20" matchText="PRICING PRIMARY MENU" />
    <message name="gotoASAPCommand" msg="ASAP" />
    <message name="gotoVENDORSCommand" msg="VENDORS" />
    <message name="LOGOFF_STRING" msg="LOGOFF" />
    <message name="PRICING_PRIMARY_MENU" msg="66" />
  </screen>
  <screen name="FREIGHTLOGIN" version="3.0.0">
    <field name="banner" x="1" y="29" length="14" matchText="Signon to CICS" /> 
	<!--<field name="banner" x="1" y="13" length="13" matchText="FedEx Freight" />-->
	<field name="userId" x="10" y="11" length="6" matchText="Userid" />
	<field name="password" x="11" y="26" length="" matchText="Password" />
	<field name="successLoginScreen" x="24" y="12" length="19" matchText="Sign-on is complete" />
	<field name="bannerT" x="1" y="23" length="36" matchText="F R E I G H T    M A N A G E M E N T" />
	<field name="userIdT" x="7" y="2" length="7" matchText="USER ID" />
	<field name="passwordT" x="7" y="43" length="" matchText="PASSWORD" />
	<field name="successLoginScreenT" x="2" y="33" length="16" matchText="TFMS RELEASE 1.5" />
	<field name="logilityProcessingTerminated" x="24" y ="2" length="21" matchText="PROCESSING TERMINATED"/>
    <field name="logilityPrimaryMenuScreen" x="2" y="2" length="21" matchText="*BASE RATE PLUS - FF*" />
    <field name="pricingPrimaryMenuScreen" x="3" y="32" length="20" matchText="AMERICAN FREIGHTWAYS" />
    <field name="primaryPassthroughScreen" x="2" y="30" length="19" matchText="Pricing Publication"/>
    <field name="ratingSubSystemMenu" x="1" y="30" length="21" matchText="RATING SUBSYSTEM MENU"/>
    <field name="d_field" x="23" y="80" length="1" matchText=""/>
    <message name="LOGOFF_STRING" msg="cesf logoff" />
    <message name="PRICING_PRIMARY_MENU" msg="tfms" />
    <message name="PRICING_PRIMARY_MENU1" msg="E00" />    
    <message name="LOGILITY_PRIMARY_MENU" msg="dsn6" />
    <message name="PRIMARY_PASSTHROUGH_SCREEN" msg="PA15"/>
  </screen>
  <screen name="GROUNDLOGIN" version="3.0.0">
    <field name="banner" x="1" y="36" length="7" matchText="Sign On" />
    <field name="userId" x="6" y="53" length="10" matchText="" />
    <field name="password" x="7" y="53" length="10" matchText="" />
    <field name="successLoginScreen" x="21" y="2" length="24" matchText="Press Enter to continue." />
    <field name="displayMessagesScreenName" x="1" y="28" length="35" matchText="Display Messages$|Display Program Messages$" />
    <field name="weeklyMileageScreenName" x="2" y="24" length="30" matchText="Weekly Mileage Reminder Screen" />
    <field name="fedexGroundScreenName" x="1" y="33" length="12" matchText="FedEx Ground" />
    <field name="fedexGroundMenuChoice" x="22" y="15" length="2" matchText="01" />
    <field name="fedexGroundMarketingDepartmentScreenName" x="2" y="23" length="35" matchText="MARKETING DEPARTMENT SELECTION MENU" />
    <field name="fedexGroundMarketingDepartmentMenuChoice" x="22" y="15" length="2" matchText="01" />
    <field name="fedexGroundStatusScreenName" x="2" y="35" length="12" matchText="STATUS  Menu" />
    <message name="LOGOFF_STRING" msg="90" />
  </screen> 	
  <screen name="FXF4C" version="1.0.0">
    <field name="screenName" x="1" y="10" length="7" matchText="4C" />
    <field name="userCode" x="5" y="13" length="2" matchText="" />
    <field name="actionInd" x="6" y="32" length="1" matchText="" />
    <field name="aalias" x="8" y="9" length="32" matchText="" />
    <field name="city" x="10" y="21" length="32" matchText="" />
    <field name="state" x="10" y="58" length="2" matchText="" />
    <field name="country" x="10" y="70" length="2" matchText="" />
    <field name="county" x="11" y="21" length="32" matchText="" />
    <field name="zipCode" x="11" y="64" length="6" matchText="" />
    <field name="indexNumber" x="12" y="21" length="4" matchText="" />
    <field name="comment" x="15" y="12" length="65" matchText="" />
	<field name="screenMessage" x="24" y="2" length="64" matchText="" />
    <message name="CANNOT_NEXT" msg="THESE ERRORS DETECTED: 202" />
	<message name="RECORD_NOT_FOUND" msg="THESE ERRORS DETECTED: 207" />
	<message name="RECORD_EXISTS" msg="THESE ERRORS DETECTED: 206" />
	<message name="INQUIRY_SUCCESS" msg="INQUIRY SUCCESSFUL" />
	<message name="ADD_SUCCESS" msg="ADD ACTION SUCCESSFUL" />
	<message name="DELETE_SUCCESS" msg="DELETE ACTION SUCCESSFUL" />
	<message name="INQ_NEXT_SUCCESS" msg="INQUIRY NEXT SUCCESSFUL" />
	<message name="INQ_PREV_SUCCESS" msg="INQUIRY PREVIOUS SUCCESSFUL" />
  </screen>  
  <screen name="FXF1" version="1.0.0">
    <field name="screenName" x="1" y="11" length="1" matchText="1" />
    <field name="DispScreenName" x="1" y="33" length="23" matchText="" />
    <field name="SR_screenName" x="1" y="6" length="3" matchText="1RD" />
    <field name="PD_screenName" x="1" y="6" length="3" matchText="2RD" />
	<field name="BC_screenName" x="1" y="11" length="1" matchText="2" />
	<field name="SC_CC_screenName" x="1" y="11" length="1" matchText="3" />
	<field name="HU_DETAIL_screenName" x="1" y="35" length="10" matchText="" />
    <field name="screenMessage" x="24" y="2" length="66" matchText="" />
    <field name="SR_rbNumber" x="8" y="55" length="8" matchText="" />
    <field name="SR_api" x="8" y="69" length="5" matchText="" />
    <field name="SR_total_chgs" x="21" y="44" length="9" matchText="" />
    <field name="PD_rbNumber" x="8" y="55" length="8" matchText="" />
    <field name="PD_api" x="8" y="69" length="5" matchText="" />
    <field name="CA_total_chgs" x="23" y="44" length="11" matchText="" /> 
	<field name="HU_Detail_Int" x="8" y="43" length="1" matchText="" />
	<field name="HU_Detail_Pc" x="8" y="49" length="1" matchText="" />
	<field name="HU_Detail_rbNumber" x="8" y="55" length="9" matchText="" />
	<field name="HU_Detail_api" x="8" y="69" length="5" matchText="" />
	<field name="HU_Detail_Curr" x="8" y="77" length="4" matchText="" />
	<field name="HU_Detail_DimFac" x="9" y="18" length="9" matchText="" />
	<field name="HU_Detail_RatAuth" x="9" y="40" length="4" matchText="" />
	<field name="HU_Detail_RatTariff" x="9" y="45" length="9" matchText="" />
	<field name="HU_Detail_RatNum" x="9" y="56" length="13" matchText="" />
	<field name="HU_Detail_RatSec" x="9" y="70" length="5" matchText="" />
	<field name="HU_Detail_RatedWght" x="22" y="47" length="8" matchText="" />
    <field name="currentDate" x="1" y="69" length="12" matchText="" />
    <field name="originServiceCenter" x="7" y="75" length="4" matchText="" />
    <field name="shipDateMonth" x="3" y="69" length="2" matchText="" />
    <field name="shipDateDay" x="3" y="74" length="2" matchText="" />
    <field name="shipDateYear" x="3" y="79" length="2" matchText="" />
    <field name="action" x="3" y="24" length="1" matchText="" />
    <field name="userCode" x="3" y="6" length="2" matchText="" />
    <field name="carrierCode" x="3" y="14" length="4" matchText="" />
    <field name="terms" x="3" y="31" length="4" matchText="" />
    <field name="billCust1Type" x="4" y="7" length="2" matchText="" />
    <field name="billCust1Code" x="4" y="10" length="43" matchText="" />
    <field name="billCust2Type" x="5" y="7" length="2" matchText="" />
    <field name="billCust2Code" x="5" y="10" length="43	" matchText="" />
    <field name="moreBillCodes" x="6" y="18" length="1" matchText="" />
    <field name="originCity" x="7" y="8" length="32" matchText="" />
    <field name="originState" x="7" y="45" length="2" matchText="" />
    <field name="originZipCode" x="7" y="53" length="6" matchText="" />
    <field name="originCtry" x="7" y="66" length="2" matchText="" />
    <field name="originTerminal" x="7" y="75" length="4" matchText="" />
    <field name="shipperCust1Type" x="8" y="7" length="2" matchText="" />
    <field name="shipperCust1Code" x="8" y="10" length="43" matchText="" />
    <field name="shipperCust2Type" x="9" y="7" length="2" matchText="" />
    <field name="shipperCust2Code" x="9" y="10" length="43" matchText="" />
    <field name="moreShipperCodes" x="10" y="24" length="1" matchText="" />
    <field name="destCity" x="11" y="8" length="32" matchText="" />
    <field name="destState" x="11" y="45" length="2" matchText="" />
    <field name="destZipCode" x="11" y="53" length="6" matchText="" />
    <field name="destCtry" x="11" y="66" length="2" matchText="" />
    <field name="destTerminal" x="11" y="75" length="4" matchText="" />
    <field name="consigneeCust1Type" x="12" y="7" length="2" matchText="" />
    <field name="consigneeCust1Code" x="12" y="10" length="43" matchText="" />
    <field name="consigneeCust2Type" x="13" y="7" length="2" matchText="" />
    <field name="consigneeCust2Code" x="13" y="10" length="43" matchText="" />
    <field name="moreconsigneeCodes" x="14" y="19" length="1" matchText="" />
    <field name="move" x="16" y="64" length="1" matchText="" />
	<field name="moreHuDetail" x="14" y="33" length="1" matchText="" />
	<field name="moreProducts" x="14" y="46" length="1" matchText="" />
    <field name="serviceDays" x="16" y="77" length="2" matchText="" />
    <field name="typeHaul" x="17" y="13" length="1" matchText="" />
    <field name="deliveringCarrier" x="17" y="25" length="4" matchText="" />
    <field name="cod" x="17" y="40" length="1" matchText="" />
    <field name="codTerms" x="17" y="52" length="1" matchText="" />
    <field name="codAmount" x="17" y="66" length="12" matchText="" />
    <field name="shipDiscPercent" x="22" y="14" length="5" matchText="" />
    <field name="classRateAdjPercent" x="22" y="38" length="6" matchText="" />
    <field name="chgAllowType" x="22" y="61" length="1" matchText="" />
    <field name="chgAllowAmount" x="22" y="71" length="9" matchText="" />
    <field name="mileage" x="23" y="9" length="5" matchText="" />
    <field name="handlingUnitType" x="23" y="23" length="4" matchText="" />
    <field name="handlingUnit" x="23" y="32" length="6" matchText="" />
    <field name="subUnit" x="23" y="43" length="6" matchText="" />
    <field name="totalWeight" x="23" y="59" length="6" matchText="" />
    <field name="cube" x="23" y="70" length="9" matchText="" />
	<!--== customer screen for Bill to customers more than 2 .-->
	<table name="BC_Codes" numRows="8" numSections="1" numColumns="2" numPages="1" startingrowx="5">
      <col name="BC_Type" y="8" length="2" matchText="" />
      <col name="BC_Code" y="11" length="43" matchText="" />
    </table>
	<!--== customer screen for ship customers more than 2 .-->
	<table name="SC_Codes" numRows="8" numSections="1" numColumns="2" numPages="1" startingrowx="5">
      <col name="SC_Type" y="8" length="2" matchText="" />
      <col name="SC_Code" y="11" length="43" matchText="" />
    </table>
	<!--== customer screen for consignee customers more than 2 .-->
	<table name="CC_Codes" numRows="8" numSections="1" numColumns="2" numPages="1" startingrowx="14">
      <col name="CC_Type" y="8" length="2" matchText="" />
      <col name="CC_Code" y="11" length="43" matchText="" />
    </table>
	<table name="tableRates" numRows="10" numSections="8" numColumns="4" numPages="3" startingrowx="11">
      <col name="TR_type" y="2" length="3" matchText="" />
      <col name="TR_weight" y="9" length="6" matchText="" />
      <col name="TR_cwt" y="17" length="7" matchText="" />	
      <col name="TR_Class" y="20" length="3" matchText="" />
      <col name="TR_type1" y="2" length="3" matchText="" />
      <col name="TR_weight1" y="9" length="6" matchText="" />
      <col name="TR_cwt1" y="25" length="7" matchText="" />	
      <col name="TR_Class1" y="28" length="3" matchText="" />
      <col name="TR_type2" y="2" length="3" matchText="" />
      <col name="TR_weight2" y="9" length="6" matchText="" />
      <col name="TR_cwt2" y="33" length="7" matchText="" />	
      <col name="TR_Class2" y="36" length="3" matchText="" />
      <col name="TR_type3" y="2" length="3" matchText="" />
      <col name="TR_weight3" y="9" length="6" matchText="" />
      <col name="TR_cwt3" y="41" length="7" matchText="" />	
      <col name="TR_Class3" y="44" length="3" matchText="" />
      <col name="TR_type4" y="2" length="3" matchText="" />
      <col name="TR_weight4" y="9" length="6" matchText="" />
      <col name="TR_cwt4" y="49" length="7" matchText="" />	
      <col name="TR_Class4" y="52" length="3" matchText="" />
      <col name="TR_type5" y="2" length="3" matchText="" />
      <col name="TR_weight5" y="9" length="6" matchText="" />
      <col name="TR_cwt5" y="57" length="7" matchText="" />	
      <col name="TR_Class5" y="60" length="3" matchText="" />
      <col name="TR_type6" y="2" length="3" matchText="" />
      <col name="TR_weight6" y="9" length="6" matchText="" />
      <col name="TR_cwt6" y="65" length="7" matchText="" />	
      <col name="TR_Class6" y="68" length="3" matchText="" />
      <col name="TR_type7" y="2" length="3" matchText="" />
      <col name="TR_weight7" y="9" length="6" matchText="" />
      <col name="TR_cwt7" y="73" length="7" matchText="" />	
      <col name="TR_Class7" y="76" length="3" matchText="" />                            
    </table>
    <table name="CA_ratedLines" numRows="12" numSections="1" numColumns="6" numPages="2" startingrowx="11">
      <col name="CA_lineNumber" y="2" length="2" matchText="" />
      <col name="CA_conditionCode" y="5" length="4" matchText="" />
      <col name="CA_description" y="10" length="20" matchText="" />
      <col name="CA_type" y="33" length="1" matchText="" />
      <col name="CA_amount" y="38" length="7" matchText="" />
      <col name="CA_line_total" y="47" length="8" matchText="" />
    </table>
    <table name="Prod_ratedLines" numRows="12" numSections="1" numColumns="9" numPages="5" startingrowx="11">
      <col name="Prod_lineNumber" y="2" length="3" matchText="" />
      <col name="Prod_class" y="7" length="6" matchText="" />
      <col name="Prod_auth" y="15" length="5" matchText="" />
      <col name="Prod_number" y="21" length="6" matchText="" />
      <col name="Prod_item" y="28" length="15" matchText="" />
      <col name="Prod_item_suffix" y="44" length="5" matchText="" />
      <col name="Prod_weight" y="53" length="6" matchText="" />
      <col name="Prod_cwt_rate" y="60" length="8" matchText="" />
      <col name="Prod_line_total" y="73" length="8" matchText="" />
    </table>
    <table name="Disc_discountLines" numRows="4" numSections="1" numColumns="7" numPages="1" startingrowx="11">
      <col name="Disc_lineNumber" y="2" length="1" matchText="" />
      <col name="Disc_auth" y="4" length="5" matchText="" />
      <col name="Disc_number" y="12" length="6" matchText="" />
      <col name="Disc_item" y="23" length="12" matchText="" />
      <col name="Disc_item_suffix" y="35" length="5" matchText="" />
      <col name="Disc_amount" y="41" length="7" matchText="" />
      <col name="Disc_type" y="50" length="6" matchText="" />
    </table>
    <table name="SR_ratedLines" numRows="13" numSections="1" numColumns="4" numPages="1" startingrowx="10">
      <col name="SR_type" y="2" length="25" matchText="" />
      <col name="SR_weight" y="27" length="6" matchText="" />
      <col name="SR_cwt_rate" y="35" length="8" matchText="" />
      <col name="SR_line_total" y="45" length="8" matchText="" />
    </table>
    <table name="conditionCodes" numRows="2" numSections="10" numColumns="10" numPages="1" startingrowx="15">
      <col name="conditionCode1" y="8" length="4" matchText="" />
      <col name="conditionCode2" y="13" length="4" matchText="" />
      <col name="conditionCode3" y="18" length="4" matchText="" />
      <col name="conditionCode4" y="23" length="4" matchText="" />
      <col name="conditionCode5" y="28" length="4" matchText="" />
      <col name="conditionCode6" y="33" length="4" matchText="" />
      <col name="conditionCode7" y="38" length="4" matchText="" />
      <col name="conditionCode8" y="43" length="4" matchText="" />
      <col name="conditionCode9" y="48" length="4" matchText="" />
      <col name="conditionCode10" y="53" length="4" matchText="" />
    </table>
    <table name="lineItems" numRows="3" numSections="2" numColumns="5" numPages="1" startingrowx="19">
      <col name="nmfcClass_1" y="11" length="4" matchText="" />
      <col name="nmfcType_1" y="16" length="1" matchText="" />
      <col name="nmfcNumber_1" y="18" length="7" matchText="" />
      <col name="nmfcSuffix_1" y="26" length="3" matchText="" />
      <col name="weight_1" y="32" length="7" matchText="" />
      <col name="nmfcClass_2" y="51" length="4" matchText="" />
      <col name="nmfcType_2" y="56" length="1" matchText="" />
      <col name="nmfcNumber_2" y="58" length="7" matchText="" />
      <col name="nmfcSuffix_2" y="66" length="3" matchText="" />
      <col name="weight_2" y="72" length="7" matchText="" />
    </table>
	<table name="lineItemsPage" numRows="19	" numSections="2" numColumns="5" numPages="1" startingrowx="4">
      <col name="nmfcClass_1" y="11" length="4" matchText="" />
      <col name="nmfcType_1" y="16" length="1" matchText="" />
      <col name="nmfcNumber_1" y="18" length="7" matchText="" />
      <col name="nmfcSuffix_1" y="26" length="3" matchText="" />
      <col name="weight_1" y="32" length="7" matchText="" />
	  <col name="nmfcClass_2" y="51" length="4" matchText="" />
      <col name="nmfcType_2" y="56" length="1" matchText="" />
      <col name="nmfcNumber_2" y="58" length="7" matchText="" />
      <col name="nmfcSuffix_2" y="66" length="3" matchText="" />
      <col name="weight_2" y="72" length="7" matchText="" />
    </table>
	<table name="HUDetailPage" numRows="17	" numSections="3" numColumns="2" numPages="1" startingrowx="6">
      <col name="cu_inches_1" y="8" length="9" matchText="" />
      <col name="weight_1" y="20" length="7" matchText="" />
	  <col name="cu_inches_2" y="35" length="9" matchText="" />
      <col name="weight_2" y="47" length="7" matchText="" />
	  <col name="cu_inches_3" y="61" length="9" matchText="" />
      <col name="weight_3" y="73" length="7" matchText="" />
    </table>
	<table name="HU_Detail_ReturnLines" numRows="12" numSections="1" numColumns="6" numPages="2" startingrowx="12">
      <col name="HU_lineNumber" y="2" length="3" matchText="" />
      <col name="HU_CubicInches" y="6" length="9" matchText="" />
      <col name="HU_ActualWght" y="16" length="9" matchText="" />
      <col name="HU_VolWght" y="26" length="10" matchText="" />
      <col name="HU_AvgWght" y="37" length="10" matchText="" />
      <col name="HU_DimWght" y="48" length="10" matchText="" />
    </table>
    <table name="Unit_PricingLines" numRows="6" numSections="1" numColumns="8" numPages="1" startingrowx="13">
      <col name="Unit_Desc" y="2" length="15" matchText="" />
      <col name="Unit_NumberOf" y="20" length="4" matchText="" />
      <col name="Unit_Weight" y="27" length="7" matchText="" />
      <col name="Unit_WeightPerUnit" y="35" length="7" matchText="" />
      <col name="Unit_ShipmentWgt" y="45" length="7" matchText="" />
      <col name="Unit_Rate" y="52" length="8" matchText="" />
      <col name="Unit_Type" y="62" length="4" matchText="" />
      <col name="Unit_line_total" y="66" length="10" matchText="" />
    </table>
    <message name="NO_PARTICAPATION" msg="THESE ERRORS DETECTED: 321" />
    <message name="INVALID_ACTION_FIELD" msg="THESE ERRORS DETECTED: 208" />
    <message name="INVALID_ORIG_CITY_NAME" msg="THESE ERRORS DETECTED: 211"/>
    <message name="INVALID_ORIG_STATE" msg="THESE ERRORS DETECTED: 212"/>
    <message name="INVALID_ORIG_CTRY" msg="THESE ERRORS DETECTED: 251"/>
    <message name="INVALID_DEST_CITY_NAME" msg="THESE ERRORS DETECTED: 215"/>
    <message name="INVALID_DEST_STATE" msg="THESE ERRORS DETECTED: 216"/>
    <message name="INVALID_DEST_CTRY" msg="THESE ERRORS DETECTED: 254"/>	
    <message name="NO_RATES_FOUND" msg="THESE ERRORS DETECTED: 370"/>
    <message name="INVALID_WEIGHT" msg="THESE ERRORS DETECTED: 235"/>
    <message name="MANUAL_RATE_FLAG" msg="THESE ERRORS DETECTED: 301"/>
    <message name="ACCOUNT_INFO" msg="THESE ERRORS DETECTED: 246"/>
    <message name="SR_SUCCESS" msg="PRESS ENTER TO VIEW PRODUCT DETAIL*"/>
    <message name="Prod_SUCCESS" msg="PRESS ENTER TO VIEW DISCOUNT DETAIL*"/>
    <message name="Disc_SUCCESS" msg="PRESS ENTER TO VIEW CHARGES*"/>
    <message name="Last_Detail_Screen" msg="PRESS CLEAR TO RETURN TO ENTRY SCREEN"/>
    <message name="SR_Screen_Name" msg="SHIPMENT RATING"/>
    <message name="Prod_Screen_Name" msg="PRODUCTS"/>
	<message name="HU_Screen_Name" msg="HU DETAIL"/>
	<message name="Prod_Entry_Screen_Name" msg="RATING AND RATE INQUIRY PRODUCTS"/>
	<message name="Geo_Screen_Name" msg="GEOGRAPHIC POINTS SELECTION"/>
    <message name="Disc_Screen_Name" msg="DISCOUNTS"/>
    <message name="CA_Screen_Name" msg="CHARGES/ALLOWANCES"/>
    <message name="Unit_Screen_Name" msg="UNIT PRICING"/>
    <message name="Arb_Screen_Name" msg="ARBITRARIES"/>
    <message name="SR_RETURN" msg="PRESS ENTER TO PROCEED"/>
    <message name="TR_SUCCESS" msg="PRESS ENTER KEY TO PROCEED*|PRESS CLEAR TO RETURN TO ENTRY SCREEN*"/>
    <message name="GENERAL_ERROR" msg="THESE ERRORS DETECTED*"/>
	<message name="MORE_PRODUCTS" msg="PRESS ENTER TO VIEW MORE PRODUCTS"/>
	<message name="NO_MORE_PRODUCTS" msg="PRESS ENTER TO VIEW CHARGES/ALLOWANCES DETAIL*"/>
	<message name="MORE_CHGS_ALL" msg="PRESS ENTER TO VIEW CHARGES/ALLOWANCES DETAIL*"/>
	<message name="NO_MORE_CHGS_ALL" msg="PRESS CLEAR TO RETURN TO ENTRY SCREEN"/>
  </screen>
  <screen name="FXFE4A" version="1.0.0">
    <field name="screenName" x="1" y="15" length="3" matchText="E4A" />
    <field name="e4aScreenDisplay" x="1" y="27" length="28" matchText="MANUAL RATE QUEUE DEFINITION" />
    <field name="currentDate" x="1" y="71" length="10" matchText="" />
    <field name="nextScreen" x="2" y="15" length="4" matchText="" />
    <field name="companyCd" x="2" y="45" length="1" matchText="1"/>
    <field name="currentTime" x="2" y="71" length="8" matchText="" />
    <field name="nextQueueType" x="3" y="12" length="4" matchText="" />
    <field name="nextQueueName" x="3" y="28" length="4" matchText="" />
    <field name="screenMessage" x="24" y="2" length="64" matchText="" />
    <table name="queues" numRows="17" numColumns="10" numPages="500" numSections="1" startingrowx="6">
      <col name="editCode" y="2" length="1" matchText="" />
      <col name="type" y="4" length="4" matchText="" />
      <col name="name" y="9" length="4" matchText="" />
      <col name="prnt" y="14" length="4" matchText="" />
      <col name="description" y="19" length="40" matchText="" />
      <col name="count" y="60" length="5" matchText="" />
      <col name="flushType" y="66" length="1" matchText="" />
      <col name="oldestBillDate" y="68" length="5" matchText="" />
      <col name="oldestBillTime" y="74" length="5" matchText="" />
      <col name="scac" y="80" length="1" matchText="" />
    </table>
    <message name="END_OF_FILE" msg="S00002: END-OF-FILE" />
    <message name="SUCCESS" msg="S00001: REQUESTED FUNCTION\(S\) COMPLETED SUCCESSFULLY" />
    <message name="EDIT_CODE_MESSAGE" msg="S00007: ENTER 'A'DD/'C'HANGE/'D'ELETE TO MODIFY DATA OR PRESS PF8 TO PAGE FWD" />
    <message name="SCAC_MESSAGE" msg="AF0004: CARRIER MUST SPECIFY 'F', 'M' OR 'C'" />
    <message name="FLUSH_MESSAGE" msg="R00029: U = UNFLUSHABLE, S = SYSTEM" />
  </screen>
  <screen name="FXFE4H" version="1.0.0">
      <field name="screenName" x="1" y="15" length="4" matchText="E4H" />
      <field name="screenMessage" x="24" y="2" length="64" matchText="" />
      <field name="pageNumber" x="1" y="24" length="3" matchText="" />
      <field name="numberOfPages" x="1" y="31" length="3" matchText="" />
      <field name="currentDate" x="1" y="73" length="8" matchText="" />
      <field name="nextScreen" x="2" y="15" length="4" matchText="" />
      <field name="inquiryNumber" x="2" y="25" length="10" matchText="" />
      <field name="inquiryNumberSuffix" x="2" y="36" length="2" matchText="" />
      <field name="originServiceCenter" x="2" y="47" length="4" matchText="" />
      <field name="shipDate" x="2" y="55" length="10" matchText="" />
      <field name="time" x="2" y="73" length="8" matchText="" />
      <field name="func" x="3" y="8" length="2" matchText="" />
      <field name="terms" x="3" y="48" length="1" matchText="" />
      <field name="destinationZipCode" x="3" y="53" length="6" matchText="" />
      <field name="destinationServiceCenter" x="3" y="63" length="3" matchText="" />
      <field name="rateReview" x="3" y="80" length="1" matchText="" />
      <field name="consigneeCode" x="4" y="5" length="10" matchText="" />
      <field name="consigneeName" x="4" y="16" length="30" matchText="" />